# NOTE: update this with your service name
service: telegram-bot

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules:
    packagePath: './package.json'
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-central-1
  role: YOUR_AWS_ROLE
  environment:
    TOKEN: YOUR_TELEGRAM_TOKEN
    AWS_DYNAMO_ENDPOINT: https://dynamodb.eu-central-1.amazonaws.com
    CURRENCIES: 'BTC XRP ETH ETC EOS KRB IOT LTC UAH ZEC EUR USD'

functions:
  cryptorateteller:
    handler: handler.handle
    timeout: 20
    events:
      - http:
          path: cryptorateteller
          method: post
          cors: true